# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guru31/CPP_Progs/BlockOne

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guru31/CPP_Progs/BlockOne

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guru31/CPP_Progs/BlockOne/CMakeFiles /home/guru31/CPP_Progs/BlockOne/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guru31/CPP_Progs/BlockOne/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named order_book_test

# Build rule for target.
order_book_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 order_book_test
.PHONY : order_book_test

# fast build rule for target.
order_book_test/fast:
	$(MAKE) -f CMakeFiles/order_book_test.dir/build.make CMakeFiles/order_book_test.dir/build
.PHONY : order_book_test/fast

#=============================================================================
# Target rules for targets named BlockOne

# Build rule for target.
BlockOne: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockOne
.PHONY : BlockOne

# fast build rule for target.
BlockOne/fast:
	$(MAKE) -f CMakeFiles/BlockOne.dir/build.make CMakeFiles/BlockOne.dir/build
.PHONY : BlockOne/fast

#=============================================================================
# Target rules for targets named order_book

# Build rule for target.
order_book: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 order_book
.PHONY : order_book

# fast build rule for target.
order_book/fast:
	$(MAKE) -f CMakeFiles/order_book.dir/build.make CMakeFiles/order_book.dir/build
.PHONY : order_book/fast

BlockOne.o: BlockOne.cpp.o

.PHONY : BlockOne.o

# target to build an object file
BlockOne.cpp.o:
	$(MAKE) -f CMakeFiles/order_book.dir/build.make CMakeFiles/order_book.dir/BlockOne.cpp.o
.PHONY : BlockOne.cpp.o

BlockOne.i: BlockOne.cpp.i

.PHONY : BlockOne.i

# target to preprocess a source file
BlockOne.cpp.i:
	$(MAKE) -f CMakeFiles/order_book.dir/build.make CMakeFiles/order_book.dir/BlockOne.cpp.i
.PHONY : BlockOne.cpp.i

BlockOne.s: BlockOne.cpp.s

.PHONY : BlockOne.s

# target to generate assembly for a file
BlockOne.cpp.s:
	$(MAKE) -f CMakeFiles/order_book.dir/build.make CMakeFiles/order_book.dir/BlockOne.cpp.s
.PHONY : BlockOne.cpp.s

Order.o: Order.cpp.o

.PHONY : Order.o

# target to build an object file
Order.cpp.o:
	$(MAKE) -f CMakeFiles/BlockOne.dir/build.make CMakeFiles/BlockOne.dir/Order.cpp.o
.PHONY : Order.cpp.o

Order.i: Order.cpp.i

.PHONY : Order.i

# target to preprocess a source file
Order.cpp.i:
	$(MAKE) -f CMakeFiles/BlockOne.dir/build.make CMakeFiles/BlockOne.dir/Order.cpp.i
.PHONY : Order.cpp.i

Order.s: Order.cpp.s

.PHONY : Order.s

# target to generate assembly for a file
Order.cpp.s:
	$(MAKE) -f CMakeFiles/BlockOne.dir/build.make CMakeFiles/BlockOne.dir/Order.cpp.s
.PHONY : Order.cpp.s

OrderBook.o: OrderBook.cpp.o

.PHONY : OrderBook.o

# target to build an object file
OrderBook.cpp.o:
	$(MAKE) -f CMakeFiles/BlockOne.dir/build.make CMakeFiles/BlockOne.dir/OrderBook.cpp.o
.PHONY : OrderBook.cpp.o

OrderBook.i: OrderBook.cpp.i

.PHONY : OrderBook.i

# target to preprocess a source file
OrderBook.cpp.i:
	$(MAKE) -f CMakeFiles/BlockOne.dir/build.make CMakeFiles/BlockOne.dir/OrderBook.cpp.i
.PHONY : OrderBook.cpp.i

OrderBook.s: OrderBook.cpp.s

.PHONY : OrderBook.s

# target to generate assembly for a file
OrderBook.cpp.s:
	$(MAKE) -f CMakeFiles/BlockOne.dir/build.make CMakeFiles/BlockOne.dir/OrderBook.cpp.s
.PHONY : OrderBook.cpp.s

OrderBookTest.o: OrderBookTest.cpp.o

.PHONY : OrderBookTest.o

# target to build an object file
OrderBookTest.cpp.o:
	$(MAKE) -f CMakeFiles/order_book_test.dir/build.make CMakeFiles/order_book_test.dir/OrderBookTest.cpp.o
.PHONY : OrderBookTest.cpp.o

OrderBookTest.i: OrderBookTest.cpp.i

.PHONY : OrderBookTest.i

# target to preprocess a source file
OrderBookTest.cpp.i:
	$(MAKE) -f CMakeFiles/order_book_test.dir/build.make CMakeFiles/order_book_test.dir/OrderBookTest.cpp.i
.PHONY : OrderBookTest.cpp.i

OrderBookTest.s: OrderBookTest.cpp.s

.PHONY : OrderBookTest.s

# target to generate assembly for a file
OrderBookTest.cpp.s:
	$(MAKE) -f CMakeFiles/order_book_test.dir/build.make CMakeFiles/order_book_test.dir/OrderBookTest.cpp.s
.PHONY : OrderBookTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... order_book_test"
	@echo "... BlockOne"
	@echo "... rebuild_cache"
	@echo "... order_book"
	@echo "... BlockOne.o"
	@echo "... BlockOne.i"
	@echo "... BlockOne.s"
	@echo "... Order.o"
	@echo "... Order.i"
	@echo "... Order.s"
	@echo "... OrderBook.o"
	@echo "... OrderBook.i"
	@echo "... OrderBook.s"
	@echo "... OrderBookTest.o"
	@echo "... OrderBookTest.i"
	@echo "... OrderBookTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

